[package]
name = "Entry"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
calamine = "0.22"
csv = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1"
