todo_file_path = "/home/loverain/dotFile_arch/entry/TODO.md"
cyber_resource_file_path = "/home/loverain/dotFile_arch/entry/CYBER_RESOURCE.md"
bill_dir_path = "/home/loverain/Projects/Entry/tmp"
weather_api_key = "SMEieQjde1C9eXnbE"