todo_file_path = "/home/loverain/dotFile_arch/entry/TODO.md"
cyber_resource_file_path = "/home/loverain/dotFile_arch/entry/CYBER_RESOURCE.md"
bill_dir_path = "/home/loverain/dotFile_arch/entry/bill/"
weather_api_key = "Sv9WAjQd08LTazEXL"